name: Cypress Tests

on:
  workflow_dispach:
    inputs:
      cli:
        description: Run by cyprass command line
        default: yarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E teste
        run: ${{ github.event.inputs.cli }}
