name: Cypress Tests

on:
  workflow_dispatch:
  
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps: 
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E teste
        run: node runner-electron.js

    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps: 
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E teste
        run: node runner-electron.js

    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_CHROME }}
  cypress-firefox-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps: 
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E teste
        run: node runner-electron.js

    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_FIREFOX }}
