name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps:
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Cypress Run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.events.input.spec }}
        env:
          CYPRESS_RECORD_KEY: c8a2aa95-2b0e-440b-9be2-657606a0415d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps:
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Cypress Run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.events.input.spec }}
        env:
          CYPRESS_RECORD_KEY: c8a2aa95-2b0e-440b-9be2-657606a0415d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps:
      - name: Get Code 
        uses: actions/checkout@v4.2.2

      - name: Cypress Run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.events.input.spec }}
        env:
          CYPRESS_RECORD_KEY: c8a2aa95-2b0e-440b-9be2-657606a0415d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
